// Generated by environment_config - defaults for local development
class HarbrEnvironment {
  static const int build = 9999999999;
  static const String commit = 'master';
  static const String flavor = 'edge';
}
